### PR TITLE
Add bare eslint check

### PR DESCRIPTION
**Pull request by matthewmturner**

### CODE REVIEW

**Comment by matthewmturner** [comment]
Not sure why this generated such a huge diff on the `package.lock` after installing eslint.  That must have introduced breaking changes as well as now test suite doesnt work.

@jmeistrich any thoughts here?

**Comment by jmeistrich** [comment]
@matthewmturner It looks like the package.lock changed because you're on a different version of npm? I'm using node 16.6.0 and npm 8.11..0. I think the lockfile format changed in npm v7? Maybe we should specific those versions in the `package.json`?

The failing test seems to be caused by a missing `react-dom` dependency. I'd say try reverting your `package.lock` change, update to npm >=7, and see if it works. If it doesn't, we may need to add a `react-dom` peerDependency?

**Comment by matthewmturner** [comment]
@jmeistrich okay i upgraded and i believe the new changes in package.lock are just related to eslint.  For the linting checks that are failing do you have a preference on how you would like to handle them?

**Comment by jmeistrich** [comment]
I think we should disable the warning of `no-explicit-any` since we use that a lot. I don't know if maybe that's bad practice and we should change it? But I don't know what would be better.

For `@ts-expect-error` we should add descriptions.

We should replace `@ts-ignore` with `@ts-expect-error`. I wasn't actually aware of `@ts-expect-error` until recently and it's a much better way to let tsc know to ignore the error there.

Do you want to add some descriptions and tweak some of those things? Or I think I can get to it in a day or two.

**Comment by matthewmturner** [comment]
I can definitely give it a shot but I wouldnt be surprised if I end up having questions on the errors.  Either way it will be a good way for me to start getting familiar with the codebase so im happy to at least give it a go.

**Comment by matthewmturner** [comment]
@jmeistrich going through this and have a few comments / questions:

- Eslint by default doesnt like the use of `debugger`.  Are you okay to remove these?
- Are you okay with me replacing types defined like `T = {}` with `T = object`?
- As an FYI I added eslint check for react hooks because i saw you had eslint comment for that
- in `observableFetch` and `useFetch` I removed a type declaration that didnt seem to be needed

Lint errors in test files that i disabled as i figured they were conveniences for testing
- no-empty functions 
- react/no-children-prop

Havent gotten to the ts-expect-error yet, will come back and do more later / tomorrow.

**Comment by jmeistrich** [comment]
> Eslint by default doesnt like the use of `debugger`.  Are you okay to remove these?

Yes, remove those. They were there for testing and I forgot to remove them before committing.

> Are you okay with me replacing types defined like `T = {}` with `T = object`?

Yes, sounds good

> As an FYI I added eslint check for react hooks because i saw you had eslint comment for that

Yes, I had that enabled in Bravely so it came across when I initially copied it. Those react rules will be good to have.

> in `observableFetch` and `useFetch` I removed a type declaration that didnt seem to be needed

Why did it not seem to be needed? That should allow typing the observable returned by the fetch. Was eslint complaining about that?

**Comment by matthewmturner** [comment]
In observables/objectFns we are getting the lint error `Don't use 'Function' as a type. The 'Function' type accepts any function-like value.  It provides no type safety when calling the function, which can be a common source of bugs` at this part:

```
const objectFns = new Map<string, Function>([
    ['get', get],
    ['set', set],
    ['peek', peek],
    ['onChange', onChange],
    ['assign', assign],
    ['delete', deleteFn],
    ['toggle', toggle],
]);
```

Given there is a finite set of function signatures, should we create a container type for those and use that instead of function?

In other areas where we get this error and it seems there could actually be any function I have simply ignored the lint error for that line.

**Comment by matthewmturner** [comment]
And regarding `observableFetch` and `useFetch` - yes, eslint was complaining that the type was unused.

**Comment by jmeistrich** [comment]
I'm not sure why it would think the type is unused? It looks to me like it's used 🤷 

For that Map I'm not really sure - if there's an easy way to type it better, go for it :). But their types appear to the user from elsewhere so this is just for internal use, and they're called with whatever parameters the user passed to the proxied function:
https://github.com/LegendApp/legend-state/blob/main/src/observable.ts#L269

So I think for our purposes having stronger typing on them isn't really necessary?

**Comment by matthewmturner** [comment]
@jmeistrich can you provide some color on what `lastNode` is doing at the file level in "src/tracking.ts"?  Eslint complaining its not used but i see it being assigned to in `updateTracking` function

**Comment by matthewmturner** [comment]
@jmeistrich I will rebase this to main.  do you think that you would be able to help with adding comments for the remaining errors?  i wasnt familiar enough with the implementation to know the appropriate explanations

**Comment by jmeistrich** [comment]
Yes, absolutely. Sorry for the delay - just got my MacBook back from repair and catching up. I'll get on finishing and merging this as soon as I can.

**Comment by jmeistrich** [comment]
@matthewmturner I made a few changes, especially in [70bddd2](https://github.com/LegendApp/legend-state/pull/84/commits/70bddd2f121b3f1f40504a7d885c6015df8a468f). Do you agree with them? If so I think we're good to merge :).

**Comment by matthewmturner** [comment]
@jmeistrich makes sense to me :)

**Pull request merged**
