### PR TITLE
Migrated to Tanstack Query v5

### LINKED ISSUE #210: Migrate @tanstack/react-query to v5
https://tanstack.com/query/latest/docs/react/guides/migrating-to-v5

### PR DESCRIPTION
**Pull request by ethras**
I migrated Tanstack Query to v5.

Callback on queries were removed some I commented them out for now 
(see https://tanstack.com/query/latest/docs/react/guides/migrating-to-v5#callbacks-on-usequery-and-queryobserver-have-been-removed)

closes #210

### CODE REVIEW

**Comment by jmeistrich** [comment]
Thanks for this! And sorry for the delay!

I wonder if we'll need to version the API so that v4 will still work? Maybe the v5 version should be duplicated to a file named useObservableQuery5?

**Comment by ethras** [comment]
Thanks for your feedback! 

Regarding versioning the API, it's a valid consideration. However, we might want to evaluate if maintaining support for v4 is necessary moving forward. If we do decide to support both v4 and v5 simultaneously, I'm not sure exactly how. Is it by aliasing (in package.json) one of them ?

**Comment by jmeistrich** [comment]
There may be some who want to update legend state but aren't ready to update Query yet, it that's a major change for them?

So I think we should just name the new v5 version as a new file, then people can import the one for the version of Query that they're using?

Or do you know if a better way to handle that? One idea could be to detect the version of Query that's being used and just do the right thing. I'm not sure how cumbersome that is, to support both at the same time? It looks like these changes aren't super extensive so maybe that's possible?

**Comment by ethras** [comment]
The upgrade to v5 is in fact quite simple there are very very few breaking changes. I don't know how to have 2 versions of Query without aliasing one of them and therefore breaking stuff. In my opinion it'd be better off just supporting the latest version of Query as there isn't any drawbacks.

**Comment by jmeistrich** [comment]
Sorry for the delay on this! I've been focused on getting the 3.0 update ready to go and haven't had a chance to dig into this.

I'm still concerned about breaking existing users that haven't upgraded Query yet. As I don't use Query myself I'm not sure how intense the changes are and I haven't had a chance to test them myself. The two things I'm worried about is some callbacks are not called anymore (like `defaultedOptions.onSuccess`) and `useQueryClient({ context: options.context });` changed to `useQueryClient(new QueryClient());`. Will those changes be breaking for users of Query v4? If so it possible to detect the version of Query and use the old method if it's v4?

**Comment by kylegillen** [comment]
@ethras any chance you could provide a fork with your changes so those of us who don't require v4 support could use it today, please? :)

**Comment by kylegillen** [comment]
Would like to help here, if I can get instructions on build steps for the source - I'm happy to try and cut a build that supports v4 & 5.

**Comment by jmeistrich** [comment]
@kylegillen You should be able to `npm run build` to build the source. That creates a `dist` folder with its own package.json in it. So if you want to install from a fork you'd just need to install from the `dist` subfolder.

Sorry for the delay on this one! I've been super busy with day job and the v3 changes. I did try to see if I could make it support both 4 and 5 but even the v4 version wasn't working. I don't use Query myself so I likely missed some of its setup steps. So your help would be very much appreciated!

**Comment by jmeistrich** [comment]
I just released version 3.0 alpha which has a new much better sync system which may fully solve remote sync so you don’t need Query. And it also includes a new Query plugin, and set it up to work with Query v5. See:
- Docs of the new sync system: https://legendapp.com/open-source/state/v3/sync/persist-sync
- Docs of the Query plugin: https://legendapp.com/open-source/state/v3/sync/tanstack-query/

So I wasn’t able to directly merge the PR but I did base it on the PR and discussion here, so thank you for the feedback ❤️

**Pull request closed without merging**
