### PR TITLE
Add a parameter to event() callback

### PR DESCRIPTION
**Pull request by JohnBerd**
Thank you for that amazing library. I am [developing a library](https://azot-dev.github.io/cortex/docs/intro) to architecture React projects and this lib is the perfect base.

I was thinking about adding a parameter to the event callback.

There is still an error in the typing, it might be related to another issue. I've noticed that, when an observable contains un unknown data, it cannot get the right typing for its observables.

Capture d’écran 2023-12-06 à 08 57 04

Without a type parameter T it is okay.

I don't know how to work so don't hesitate to tell me if I should open an issue related to the pull request and/or one related to the typing issue.

Cheers :)

### CODE REVIEW

**Comment by JohnBerd** [comment]
The more I can do for this PR, no choice to use casting. I open an issue.

**Comment by JohnBerd** [comment]
Is it possible to relaunch a CI?

**Comment by jmeistrich** [comment]
Sorry for the delay on this!

I'm curious what is your planned usage of this? And how is an event with a value different from just an observable or a computed?

**Comment by JohnBerd** [comment]
No problem :)

The goal would be to send a message in a snackbar for example. I am using a unique store in my app and I have no interest to store the information.

With the current implementation I guess I would have to create an event for each message and listen to each of them.
By sending a payload, I could listen to one event and do whatever I want with that payload in this unique listener

Does it make sense for you?

**Comment by KartikBazzad** [comment]
Any progress on the merge of this PR?

**Comment by JohnBerd** [comment]
Hi @KartikBazzad you are completely right about the fire callback, I changed that part, my code didn't make sense. Thank you for the effort of writing all of this.
If I well understand, the `get` method in an event is not to meant to be accessed but to trigger the onChange.
I guess the aim of an event is to inform its subscribers when it changes, but I don't think subscriber should access the data as they want, in that case I would prefer to use an observable with an onChange, in order not adding too much code to the library.

**Comment by KartikBazzad** [comment]
the onChange event will fire whenever the observable value changes, so when you are listening and make changes to same observable it will go into infinite loop; instead use this event handler 
```typescript


interface IEvent<P = unknown, T extends string = string> {
  name: T;
  callback: (action: IAction<P, T>) => void;
}

interface IAction<P = unknown, T extends string = string> {
  name: T;
  payload: P;
}

export class EventHandler {
  private events: IEvent[] = [];
  addListener(event: IEvent) {
    this.events.push(event);
  }
  dispatch() {
    return (action: IAction) => {
      const eventsToCall = this.events.filter(
        (event) => event.name === action.name
      );
      eventsToCall.forEach((event) => {
        event.callback(action);
      });
    };
  }
}
```

```typescript

export const eventHandler = new EventHandler();

eventHandler.addListener({
  name: "Login Listener",
  callback(action) {
    console.log({ action });
  },
});

eventHandler.dispatch()({ name: "Login Listener", payload: { t: 0 } });
eventHandler.dispatch()({ name: "Login Listener", payload: { x: 1 } });
eventHandler.dispatch()({
  name: "Login Listener",
  payload: { hello: "world" },
});
```

**Comment by JohnBerd** [comment]
Closing

**Pull request closed without merging**
