### PR TITLE
Add pagination to `observableFetch`

### PR DESCRIPTION
**Pull request by matthewmturner**

### CODE REVIEW

**Comment by matthewmturner** [comment]
@jmeistrich ive started hacking together pagination for observable fetch and adding some tests as well.  fighting typescript right now though with how im aggregating all the pages data. specifically around how `t extends unknown` but when i combine api results i get `any[]` which isnt compatible. let me know if you have any thoughts on that.

in general my approach for pagination is:
- Add a parameter `paginateFn` to `observableFetch` that extracts from the first api response the total number of pages
- Use the total number of pages to construct list of urls
- use `Promise.all` to make remaining api calls
- flatten results into a single list and add to observable data

happy to get your thoughts on that as well.

**Comment by chakrihacker** [comment]
Any reason to fetch all the pages eagerly??

**Comment by jmeistrich** [comment]
My general feedback (not based on how you're doing it - just a general thought) is to try to match the behavior of other popular libraries so that it works as expected for people migrating over. I think if we have different behavior there should be a good reason for it.

**Comment by matthewmturner** [comment]
@chakrihacker i just started with that as the use case i have needed to get all data before i could continue.

@jmeistrich yeah ive been looking at TanStack Query (which I havent used before but seems very popular) but i guess i deviated a little bit.  I'll keep playing around with it.  I'm still figuring out what the ideal API would be in the case of legend state.

**Comment by matthewmturner** [comment]
A possible API, drawing inspiration from react query.

```
const page = observable(1) // This can be changed in app with Next button or something similar
const { loading, data, error, errorStr, isPrevious } = observableFetch(url, page, keepPreviousData)
```

And then within `observableFetch` I can use `page.onChange` to fetch the next page of results and mark previous data.

Separately, I could come up with another function like `observableFetchAll` for my use case to get all pages automatically.

**Comment by matthewmturner** [comment]
as an fyi i am still working on this.  currently seeing how this could work without updates to existing API.

**Pull request closed without merging**
