### PR TITLE
Add API Reference to documentation

### PR DESCRIPTION
**Pull request by matthewmturner**

### CODE REVIEW

**Comment by matthewmturner** [comment]
All I've done so far is run the command to generate markdown docs - haven't cleaned up yet.

**Comment by matthewmturner** [comment]
Just as a point of reference I added HTML docs as well.  The directory structure with html breaks out functions, variables, types into their own directories with files for each item within which i think is nice but not sure how that plays with your Nextjs setup.  On the other hand the markdown only outputs a directory for interfaces and then everything else is in the modules.md.  I can just as easily update the commands to use the markdown output if that plays easier with existing system.

@jmeistrich let me know how you would like to proceed.

**Comment by jmeistrich** [comment]
I think it may be easier to put the API reference at its own subdirectory that just uses the HTML files. I got modules.md to render within our system but it's totally unstyled and the paths to other api pages would need changing. 

I wonder if it would be better to just migrate to a more standard docs system like Docusaurus instead of making more and more big changes to our custom solution?

And if we go down this path we'd want to add a lot more typedoc comments into the code to fill out the descriptions, right? It looks pretty barebones as it is?

**Comment by matthewmturner** [comment]
@jmeistrich I definitely agree that more comments would be helpful.  im 50/50 on whether that should be done before publishing or if we just get the docs up first and then iterate from there.  do you have a preference?  and you actually already have a lot of the content that i think could be used as a first step in your existing legend-state website.  Would you be okay with moving that into the typedoc / code comments and that could be considered v1 of docs?

I do tend to agree that it would make sense to get setup with Docusaurus now.  What do you think about creating a new repo like legend-docs to hold that?  I assume it would have docs for legend-state and legend-motion.  Also how would you want to manage the relationship between the doc site and existing Legend Open Source site?

**Comment by matthewmturner** [comment]
Actually I'll reframe the question about the relationship to existing legend open source site. 

Would the idea be the replace existing legend open source pages with what docosaurus creates? Or create a dedicated legend open source domain / website? Or something else?

**Comment by matthewmturner** [comment]
I think its safe to close this based on our other conversation

**Pull request closed without merging**
