### PR TITLE
Start adding benchmarks

### PR DESCRIPTION
**Pull request by matthewmturner**

### CODE REVIEW

**Comment by matthewmturner** [comment]
@jmeistrich FYI this is very simple right now but is roughly what i had in mind.  Basically

- Add new benchmarks directory
- Add data directory within that would have common set of data that benchmarks run against
- Have directories for each benchmark types.  For now I just have micro-benchmarks but i can imagine adding others, for example to benchmark legend itself or other libraries for comparison
- Each benchmark gets its own folder where the compared approaches each get their own js file
- A shell script that handles running the benchmark against the relevant dataset

Let me know if any thoughts.

**Comment by jmeistrich** [comment]
This looks good to me. Can hyperfine be added as a devDependency or does it need to be installed globally?

**Comment by matthewmturner** [comment]
It's installed globally.  Im going to include directions in a README in the benchmarks directory for installing and how to run benchmarks

**Comment by jmeistrich** [comment]
Ok cool, sounds good. I think let's get at least one good benchmark in here as a starting point and then we can merge it? Or do you want to add a few? Would you like to mark this PR as a draft until you think it's ready to merge?

**Comment by matthewmturner** [comment]
@jmeistrich i prefer the incremental approach so definitely good to merge this one to get the ball rolling.  i think it would just be good if you could test the benchmark yourself to make sure im not the only person it works for.

Also are you okay with the first benchmark i added on for loop vs forEach?  Should other data sets be added? Or is it more nuanced than what i put?  From what I see theres basically no difference between the two approaches.

**Comment by jmeistrich** [comment]
I just tested it and it works well for me. And this does seem like a good starting point.

Once concern is that Node seems to have very different performance characteristics than browsers. I had looked at these benchmarks which suggested that for loop is 50-75% faster than forEach depending on the browser:
1. https://jsbench.me/7ejagsewtr
2. https://www.measurethat.net/Benchmarks/Show/10352/0/foreach-vs-for-len-vs-for-in-vs-for-of-vs-babel-for-of

So for best accuracy maybe we need to also make web benchmarks for each test, and if we make any decisions based on benchmarks I think we need to consider all platforms?

**Comment by matthewmturner** [comment]
@jmeistrich very interesting.  yes, definitely makes sense to bring in web and hermes engines.

From what ive [seen](https://hermesengine.dev/docs/building-and-running#executing-javascript-with-hermes) you can run arbitrary js with hermes.

And for JavaScriptCore I imagine I can write some Swift.

In the target setup then ill probably have 3 shell scripts (`node-bench.sh`, `jsc-bench.sh`, `hermes-bench.sh`) and maybe ill make an aggregator to summarize the results.

**Comment by matthewmturner** [comment]
But assuming your okay with the data and the actual code of the first benchmark then we can probably merge this and ill work on adding the other engines as a follow on.

**Comment by jmeistrich** [comment]
JavaScriptCore testing would be for non-Hermes React Native? I think we could probably skip that since Hermes is becoming the default?

Sounds good, I'll merge.

**Comment by matthewmturner** [comment]
@jmeistrich i thought JavaScriptCore would be more for the web since Legend-state can be used with React.

**Comment by jmeistrich** [comment]
Oh yeah, good point. That would be good for measuring Safari, but Chrome and Firefox have different performance. Would it be better to duplicate these tests in one of the web-based benchmarking tools, so we could test it in a few different browsers? Or is there a way to do that from hyperfine?

**Comment by matthewmturner** [comment]
From my cursory research it didnt seem too difficult to run arbitrary js code with JavaScriptCore using Swift/Obj-C (dont hold me too that).  My naive hope was that it was simple to do the same with V8.  So I was kind of expecting to be able to define a js file that is the target of the benchmark and then create runners for different engines (hermes, jsc, v8) that just point at the js file.

However, being relatively new to js im already running into some [issues](https://github.com/facebook/hermes/issues/884) due to my limited knowledge of the js ecosystem and the boundaries between js language and the engines.  But thats also one of the reasons that I wanted to get involved here - to level up my js skills. So im happy to dig into this.

Generally speaking, and to the extent practical, I think it would be nice to have a self contained benchmark suite that didnt rely on external sites.  In particular, because of the presence of hermes which isnt on the other sites (and im building a react native mobile app so thats my focus).

On a separate but related note I think we also need to make sure were aligned on the metric that is used to measure performance.  hyperfine gives us a time output but these other js benchmark tools are measuring ops/second which is probably more precise.  Do you have a preference here?  If we decide to own the benchmarking suite then of course we could just do both especially since timing with hyperfine is quite easy.

Benchmarking is quite the subject :)

**Comment by matthewmturner** [comment]
Actually maybe we could back into the ops per second based on the execution time

**Comment by jmeistrich** [comment]
I wonder if there already benchmark suites for these microbenchmarks? It seems like something a lot of people would want, so maybe it's already out there? Or if you're having fun doing it yourself, enjoy 😂

Sounds good to me though. Ops per second is probably the best metric to think about, and I think that's how most benchmarks measure things?

**Comment by matthewmturner** [comment]
@jmeistrich aha well i am enjoying it but i would only go down the rabbit hole to the extent we thought it was valuable to the project.  If this is something you would prefer keeping out of scope of the project then i would understand.

i think one important point though is distinguishing microbenchmarks vs integration / legend benchmarks.  maybe we dont necessarily view microbenchmarks as critical for benchmarking within legend but if we want to do integration / legend benchmarks the same way (i.e. node, web(JSC/V8), mobile(hermes) then maybe its worth setting the foundation up anyway and just starting with a few of the microbenchmarks as a testing ground.

**Comment by matthewmturner** [comment]
Cool - I will keep on it then.

**Pull request merged**
