### PR TITLE
Session storage

### PR DESCRIPTION
**Pull request by minorgod**
* Added a sessionStorage persist plugin
* Added .nvmrc file 
* Updated typescript and and related deps in package-lock.json. 

I'm confused as to why there isn't a config option for local-storage persist plugin to use sessionStorage instead of localStorage. I think that would probably be better, but until someone has time to do that I just duplicated the existing localStorage persist plugin since they have identical interfaces. Ran a search/replace on 'local' and replaced with 'session. Did the same for tests and they all pass. 

I had to upgrade typescript to the latest 5.x version to get the typescript errors to disappear. That's the only reason I updated the package-lock.json.

### CODE REVIEW

**Comment by jmeistrich** [comment]
Cool, thanks! But to reduce duplication I think it would be better to implement it with class inheritance - a `ObservablePersistLocalSessionStorage` would implement all of the logic and subclasses for local and session storage could pass in `localStorage` or `sessionStorage` to the constructor. Or do you think there's a cleaner way to do it?

Also the typescript version is already the latest 5.1.6 and package-lock.json has a ton of changes in babel plugins. What was it that needed updating?

**Comment by minorgod** [comment]
> Cool, thanks! But to reduce duplication I think it would be better to implement it with class inheritance - a `ObservablePersistLocalSessionStorage` would implement all of the logic and subclasses for local and session storage could pass in `localStorage` or `sessionStorage` to the constructor. Or do you think there's a cleaner way to do it?
> 
> Also the typescript version is already the latest 5.1.6 and package-lock.json has a ton of changes in babel plugins. What was it that needed updating?

I think you are correct about the class inheritance. Honestly I was just offering the PR as a quick-and-dirty solution. Partly just to see if I could hack a solution together in a few minutes, and partly to familiarize myself a bit with the project code. I've gone on a deep dive into React state management libraries over the past couple of weeks and my use case is better suited for sessionStorage persistence than localStorage. 

As for the Typescript dependencies, all I can tell you is that when I checked out the repo and ran `npm i`, I had lots of red squiggly lines in my IDE and type introspection didn't seem to be working correctly. I did initially run `npm i` with Node 12.x before I realized there was no `.nvmrc` file in the repo -- I've gotten so used to my dev environment automatically switching to the proper node version that I forgot some ppl don't use an `.nvmrc` file.  But when I switched to node 16 and ran `npm i` again, it still didn't resolve the issues. So then I ran `npm i -D typescript@5`, and suddenly all the issues went away. Maybe I just needed to delete node_modules before re-running `npm i` with the correct Node version?

Anyway, thanks for taking the time to review the PR. I can close it and hope someone implements sessionStorage properly, or if I have time I might take a stab at doing it correctly. I don't do a lot of work with Typescript/Javascript classes, but in theory I could probably figure it out.

**Comment by jmeistrich** [comment]
It could be a fun exercise to learn more about classes if you'd like to try it. Otherwise I think it's still a good idea so if you want to close the PR would you like to open an issue referencing it and maybe someone else (or I) will go for it?

**Comment by minorgod** [comment]
@jmeistrich I took a stab at doing it more correctly last night and just managed to break the localstorage/sessionstorage tests. Not sure if I'm way off or just a little off. Maybe you could give it a look? 
[Here's the diff.](https://github.com/LegendApp/legend-state/compare/main...minorgod:legend-state:session-storage-redux?expand=1)

**Comment by jmeistrich** [comment]
Ah that's getting close!

It's not ideal to make the session choice part of the options and initialize though, because that we we have can only have one storage plugin that's for either local or session storage, and can't support both at once. It would be better to have to separate storage plugins for each, which we can do with some inheritance, something like this:

```ts
class ObservablePersistLocalStorageBase implements ObservablePersistLocal {
    constructor(storage: Storage) {
        this.storage = storage;
    }
    // All of your changes except the initialize function
}

export class ObservablePersistLocalStorage extends ObservablePersistLocalStorageBase {
    constructor() {
        super(localStorage);
    }
}
export class ObservablePersistSessionStorage extends ObservablePersistLocalStorageBase {
    constructor() {
        super(sessionStorage);
    }
}
```

**Comment by minorgod** [comment]
@jmeistrich Damn, of course! Thanks so much for helping me! Now my last question...should I keep the sessionStorage tests in a separate file or add them into the localStorage tests? I'm guessing I should add them into the localStorage tests so it's not just a bunch of duplicate code in there.  I'll open a new PR in the meantime.

**Comment by minorgod** [comment]
Closing this and opening a new PR with the suggestions from @jmeistrich

**Pull request closed without merging**
